// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	parser "github.com/patyukin/mdb/internal/database/compute/parser"
	mock "github.com/stretchr/testify/mock"
)

// Compute is an autogenerated mock type for the Compute type
type Compute struct {
	mock.Mock
}

// ProcessRequest provides a mock function with given fields: request
func (_m *Compute) ProcessRequest(request string) (*parser.Command, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRequest")
	}

	var r0 *parser.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*parser.Command, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(string) *parser.Command); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parser.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCompute creates a new instance of Compute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *Compute {
	mock := &Compute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
